linters-settings:
  errcheck:
    ignore: fmt:.*,io/ioutil:^Read.*
    ignoretests: true
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - prealloc
    - unconvert
    - errcheck
    - gofmt
    - goimports
    - gosec
    - ineffassign
    - misspell

run:
  # default concurrency is a available CPU number.
  # concurrency: 4 # explicitly omit this value to fully utilize available resources.
  deadline: 5m
  issues-exit-code: 1
  tests: false

# output configuration options
output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    # we aren't calling unknown URL
    - text: "G107" # G107: Url provided to HTTP request as taint input
      linters:
        - gosec
    # we're shelling out to known commands, not relying on user-defined input.
    - text: "G204" # G204: Audit use of command execution
      linters:
        - gosec
