version: "2"
run:
  issues-exit-code: 1
  tests: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - bodyclose
    - gosec
    - misspell
    - prealloc
    - unconvert
  settings:
    errcheck:
      exclude-functions:
        - fmt.*
        - Read.*
    misspell:
      locale: US
    staticcheck:
      checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022",  "-QF1006", "-QF1008"] # default, and exclude 1 more undesired check
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: G107
      - linters:
          - gosec
        text: G204
      - linters:
          - gosec
        text: G306
      - linters:
          - gosec
        text: G115
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax

